### PR TITLE
scribble/text-render: support `(linebreak)`

### PR DESCRIPTION
**Pull request by LiberalArtist**
Here's an attempt at an implementation, tested so far only on my current draft of https://github.com/racket/racket/pull/4301.

Related to https://github.com/racket/racket/pull/4301
Closes https://github.com/racket/scribble/issues/333

### CODE REVIEW

**Comment by LiberalArtist** [comment]
I've fixed the commit message here (thanks @sorawee!).

**Comment by mflatt** [comment]
For testing, probably there should be a new document that uses `linebreak` in `scribble/scribble-test/tests/scribble/docs`.

**Comment by LiberalArtist** [comment]
Thanks, I've added a test.

**Comment by samth** [comment]
I don't know this code at all, but is the extra complexity all about line-wrapping? And is the character-at-a-time communication this now has going to be a performance issue?

**Comment by mflatt** [comment]
I don't think this will be a performance issue compared to everything else that goes into running and rendering a document, and I wasn't able to detect a performance change by trying some tests and the build guide.

**Pull request merged**
