### PR TITLE
Last,First format for names in bibtex

### PR DESCRIPTION
**Pull request by jsmaniac**
Handles comma-separated Last,First and Last,Jr,First format for names in bibtex, as well as `von`, `de la` and `van der` separators.

Note that this patch does not add support for disambiguating braces as bibtex normally supports, e.g. `{first fst} {last lst}`. That would require a more involved parser.

### CODE REVIEW

**Comment by jsmaniac** [comment]
Note: Excluding the support for braces, I followed the syntax for names as described here: http://tex.stackexchange.com/questions/557/how-should-i-type-author-names-in-a-bib-file

**Comment by jsmaniac** [comment]
Hm, it seems I have introduced somehow a regression, `Chang, Knauth and Greenman@~cite{chang2017type-systems-as-macros}` gives me `bibtex: Unknown citation "chang2017type-"`. Let me investigate this, I'll post back soon.

**Comment by jsmaniac** [comment]
Fixed, the bug was simply that `\\s` requires `#px`, and the regexps were using `#rx`, so `\\s` was interpreted as a plain `s`, and `~cite` was splitting on occurrences of `s`, not on spaces :) .

The PR should be good now.

**Comment by bennn** [comment]
re: `von` etc, I do think you should change to accept any word that starts with a lowercase letter. I guess you found some docs, and I found this while reading your stackexchange link

> BibTeX knows where one part ends and the other begins because the tokens in the von part begin with lower-case letters.

http://nwalsh.com/tex/texhelp/bibtx-23.html

After that, I think we should merge 👍

**Comment by jsmaniac** [comment]
@bennn Done!

**Comment by bennn** [comment]
Word! I sent Matthew a ping on slack to look --- because I'm nervous about seizing authoring and clicking the "merge" button. But if he's busy then I'll summon the courage tomorrow morning.

One nagging question in the meantime: should all the `.*` be `[^\\s]*`?

**Comment by mfelleisen** [comment]
@bennn push Ben push!

**Comment by jeapostrophe** [comment]
Amen

**Comment by jsmaniac** [comment]
@bennn Thanks for merge :) . The `.*` actually do and should catch spaces, e.g. in `Last L, First Name`. The ambiguity arises when there are more than three commas, `a,b,c,d`, the regexp will currently treat it as last=`a,b` junior=`c` first=`d`, but I'm not sure if that's how BibTeX handles it (or if BibTeX sees it as last=`a` junior=`b` first=`c,d`, or some other combination). Putting more than three commas is asking for trouble anyway, and should not happen.

**Pull request merged**
