### PR TITLE
Implement support for converting values to GIFs

### LINKED ISSUE #231: Support for converting values to GIFs
I'd like to write some documentation with example code that includes embedded animations. I assumed I'd be able to do this by making the animations implement the `prop:convertible` interface and support conversion to GIFs. But according to the docs for [`render-convertible-as`](https://docs.racket-lang.org/scribble/core.html?q=special#%28def._%28%28lib._scribble%2Fhtml-properties..rkt%29._render-convertible-as%29%29), it looks like only the PNG and SVG formats are supported. Is GIF support reasonable?

### PR DESCRIPTION
**Pull request by jackfirth**
Closes #231. This pull request only touches the HTML rendering implementation code; it has no tests and does not yet update the docs. I'd like to get some feedback on whether this is the right implementation approach before getting to tests and docs.

### CODE REVIEW

**Comment by jackfirth** [comment]
Manually tested this on my machine and it works. But I don't how to write an automated test for this, or which places in the documentation need to be updated. Suggestions greatly appreciated!

**Comment by samth** [comment]
Looking at the existing tests, I don't see anything that tests any aspects of the html rendering. 

A number of places (core.scrbl, running.scrbl) seem to mention the supported formats. 

There's also the `--convert` flag, which should maybe also accept `gif`, and the `render-convertible-as` property. I don't know if it makes sense to change all these, but it might be worth looking at.

**Comment by jackfirth** [comment]
I see a `++convert` flag, but not a `--convert` one. The `++convert` one already accepts gifs I think. From what I can decipher it's only the `prop:convertible` mechanism that doesn't accept gifs, images added with `@image{}` can be png, svg, or gif.

**Comment by jackfirth** [comment]
Changed `render-convertible-as?` to allow gifs. Skipping tests since manual testing seems to work and I have no idea how to set up html rendering tests.

**Comment by mflatt** [comment]
Ok by me. Is it worth extracting the GIF width and height to include as attributes in the `img`?

**Comment by soegaard** [comment]
Den tor. 21. maj 2020 kl. 05.07 skrev Sam Tobin-Hochstadt <
notifications@github.com>:

> There's also the --convert flag, which should maybe also accept gif, and
> the render-convertible-as property. I don't know if it makes sense to
> change all these, but it might be worth looking at.
>
As far as I know, there is only one reason to use gifs namely to display
animations.
For all other purposes the existing image formats are better.
Therefore a general convert-to-gif option isn't worth it.

/Jens Axel

**Comment by jackfirth** [comment]
@mflatt Yes, that's a good idea. Will update the PR.

**Comment by jackfirth** [comment]
@mflatt Done!

**Pull request merged**
