### PR TITLE
swap latex rendering of phi and varphi

### PR DESCRIPTION
**Pull request by stchang**
I think `phi` and `varphi` are flipped? eg,

```
#lang scribble/base
ϕφ
```

renders (pdf) as: φϕ

### CODE REVIEW

**Comment by bennn** [comment]
yes they are flipped

```
\documentclass{article}
\begin{document}
\[\mbox{\tt phi} = \phi\]

\[\mbox{\tt varphi} = \varphi\]
\end{document}
```

screen shot 2017-07-11 at 13 31 03

**Comment by rfindler** [comment]
Maybe worth checking \varpi and \pi too? I recall trouble with all four of those in the past.

**Comment by stchang** [comment]
The other `varX` letters (`varpi`, `varepsilon`, `varrho`, and `varsigma`) seem consistent with their latex rendering.

**Comment by rfindler** [comment]
Thanks!

**Pull request merged**
