### PR TITLE
Fixes bug #44 (Re-provided identifiers are not tracked across submodules)

### PR DESCRIPTION
**Pull request by jsmaniac**

### CODE REVIEW

**Comment by bennn** [comment]
Looks good

**Comment by jsmaniac** [comment]
I tested this more properly (by installing minimal racket, this patched version of scribble, then the full `main-distribution` package on top of that), and it seems to work fine.

The [example module](https://github.com/jsmaniac/example-bug-track-submodule-issue43.git#40c26708c8bec0041a1df444775d6f55161b9e5a) from bug #44 which re-provides `stx-map` via a submodule works fine with this PR (the identifier `stx-map` is correctly hyperlinked to its original definition, whereas it was underlined in red before).

**Comment by jsmaniac** [comment]
@bennn Just a quick ping, could this be merged before the branch for 6.7 is created (I saw on IRC it should happen tomorrow)?

I've been dog-feeding this patch for a while now, and it works fine. Without it, the documentation for some of my modules is covered with identifiers typeset with a red underline, e.g.:

http://docs.racket-lang.org/phc-toolkit/Syntax_object_manipulation_utilities.html#%28part._.Transformers_utilities%29

On my machine, with this patch, the document displays fine without red hyperlinks, so I was hoping this could be fixed with the next release.

Thanks!

**Comment by stamourv** [comment]
Merged. Sorry for the delay!

**Pull request closed without merging**
