### PR TITLE
Run Resyntax on scribble/private

### PR DESCRIPTION
**Pull request by jackfirth**
This one is a continuation of #363, this time expanded to the entire `scribble/private` collection.

### CODE REVIEW

**Comment by mflatt** [comment]
These improvements look really good — thanks!

**Comment by mfelleisen** [comment]
If resyntax also tore apart 2,000 line syntax functions, it would be perfect :-)

**Comment by rfindler** [comment]
I am a little bit hesitant of the (-> any/c boolean?) to predicate/c
transformation. I feel like the former is easier to read.

Robby

**Comment by rfindler** [comment]
Looks like it does! yay. :) 
```
#lang racket
(struct s ())
(eq? (contract (-> any/c boolean?) s? 'pos 'neg) s?) ;; => #t
```

**Comment by jackfirth** [comment]
Perfect! Then I think it's time to update the docs for `predicate/c` to say it's now an obsolete alias for `(-> any/c boolean?)`, and the latter should just be used directly instead.

**Pull request merged**
