### PR TITLE
defsubidform and its document

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by sorawee** [comment]
It looks good to me (unless you want to add `maybe-kind maybe-link` to make it match `defidform`).

**Comment by dannypsnl** [comment]
> It looks good to me (unless you want to add `maybe-kind maybe-link` to make it match `defidform`).

I think current one is ok for me

**Comment by dannypsnl** [comment]
remind, does any problem need to resolve here?

**Comment by mflatt** [comment]
Sorry for the delay, I was just looking at this now and about to merge. (It needs a version bump and history note, but I can add that after.)

Did you close because there didn't seem to be activity, or some other reason?

**Comment by dannypsnl** [comment]
Yes, it didn’t seem to be activity :)

**Comment by mflatt** [comment]
Ok! Sorry again for the delay, but I'll merge now.

**Pull request merged**
