### PR TITLE
autobib: add contracts to `*-location` functions

### LINKED ISSUE #105: scriblib/autobib not checking contracts
The incorrect expression `(journal-location "Some Journal" #:pages "1-10")` reports this very low-level error instead of a contract violation for the `#:pages` argument, which is documented as having the contract `(or/c (list/c any/c any/c) #f)`:
```
.../kw.rkt:1170:47: car: contract violation
  expected: pair?
  given: "1-10"
```

### PR DESCRIPTION
**Pull request by bennn**
Also make sure those functions convert their inputs to strings
and fix a documentation bug in `techrpt-location`

Closes #105

### CODE REVIEW

**Comment by LeifAndersen** [comment]
LGTM

**Comment by LeifAndersen** [comment]
Hey @bennn , it looks like this conflicts now. (Just in the tests file, which can honestly probably get merged by hand.)

**Comment by bennn** [comment]
Thanks for the notice, I pushed a fix
(and converted your tests to rackunit)

**Comment by LeifAndersen** [comment]
Alright then, LGTM...again. :)

**Comment by LeifAndersen** [comment]
Unless @mflatt has any complaints about this, I would go ahead and update it.

Otherwise perhaps update the history?

**Pull request merged**
