### PR TITLE
Closes #61

### LINKED ISSUE #61: HTML not responsive enough
The generated HTML is not responsive, IR won't look good on mobile devices.

### PR DESCRIPTION
**Pull request by SpooikypokDev**
Closes #61. Adds better mobile phone support for the generated HTML. Menus are atop the page. Maybe find a better way to do that.

### CODE REVIEW

**Comment by samth** [comment]
@mbutterick is probably the right person to review this.

**Comment by mbutterick** [comment]
I would reject this PR. I see the issue referenced in #61. But this patch does not fix it.

More broadly, I don't think it’s worthwhile to try to make the docs work on mobile phones. The code samples can't be reduced in any reasonable way. For instance, [Rust](https://doc.rust-lang.org) wraps the code samples (which looks terrible). [Go](https://golang.org/doc/) and [Swift](https://developer.apple.com/reference/swift/string) put them in horizontally scrolling boxes (which looks terrible too). 

Racket does nothing, which may also look terrible, but at least keeps us competitive.

But I'll make you a deal: post an example of programming-language documentation that does a better job, and I'll reconsider the matter.

**Comment by SpooikypokDev** [comment]
Godot docs: http://docs.godotengine.org/en/stable/index.html

**Comment by mbutterick** [comment]
These docs don't have the same problem because they don't rely on code samples to the same degree. But the few that exist are in horizontally scrolling boxes. If I have more time to think about this down the line, I will. But for now, case closed.

**Pull request closed without merging**
