### PR TITLE
Fix eval:check in interaction to properly validate its arguments

### LINKED ISSUE #9: Using eval:check in interaction doesn't seem to work
Even this simple usage of `eval:check` fails:

```racket
#lang racket/base
(require scribble/eval)
(interaction (eval:check #t #t))
```

```
eval: example result check failed in: #t
```

What's wrong?

### PR DESCRIPTION
**Pull request by lexi-lambda**
Fixes #9.

### CODE REVIEW

**Comment by lexi-lambda** [comment]
@rfindler Quick ping to check if someone saw this and/or remembers it still exists. :wink: I'd appreciate if you (or someone else) could take a look, but there's no rush, obviously.

**Comment by rfindler** [comment]
I didn't write eval:check, but from looking at the diff, I wonder if this is backwards compatible. Like it is going to require an extra quote now for some results?

**Comment by lexi-lambda** [comment]
It was my understanding that `eval:check` is currently just broken—that is, it doesn't work at all. Perhaps I'm mistaken, but I couldn't figure out how to make it work properly.

**Comment by lexi-lambda** [comment]
I did a little bit of digging to see where this code came from. I looks like `eval:check` was added in 2008 by @mflatt, and the relevant code appears to have been most recently modified by @elibarzilay. Can anyone confirm how recently this worked?

**Comment by rfindler** [comment]
I cannot but I guess git is more reliable than anyone's memory anyways. I
would also look for test cases and uses of it in the docs too, just to be
safe.

Robby

**Comment by lexi-lambda** [comment]
I didn't find anything at all grepping through the codebase for `eval:check` besides the implementation and the brief note in the docs. As far as I can tell, it's unused.

**Comment by stamourv** [comment]
Merged, thanks!

**Pull request closed without merging**
